binaries = ['mdadm']

[imports.build_tasks]
"ugrd.fs.mdraid" = [ "generate_mdadm_conf" ]

[imports.init_main]
"ugrd.fs.mdraid" = [ "md_init" ]

[import_order.before]
md_init = ["mount_fstab", "handle_resume"]
