__version__ = "0.3.1"

from zenlib.util import contains


@contains("hostonly", "Skipping mdadm.conf generation, hostonly mode is disabled.", log_level=30)
def generate_mdadm_conf(self) -> None:
    """Generates /etc/mdadm.conf inside the build directory from `mdadm --detail --scan`.

    The host's /etc/mdadm.conf is intentionally NOT copied: it often carries
    stale ARRAY entries, duplicated names, or restrictive DEVICE globs that
    prevent `mdadm --assemble --scan` from finding all components when run with
    MDADM_NO_UDEV=1 in the initramfs.
    """
    try:
        cmd = self._run(["mdadm", "--detail", "--scan"])
    except RuntimeError:
        return self.logger.warning("mdadm --detail --scan failed; not writing /etc/mdadm.conf.")

    arrays = cmd.stdout.decode().strip()
    if not arrays:
        return self.logger.warning("mdadm --detail --scan returned no arrays; not writing /etc/mdadm.conf.")

    contents = ["# Generated by UGRD ugrd.fs.mdraid", "DEVICE partitions", "", arrays, ""]
    self._write("/etc/mdadm.conf", contents)


def md_init(self) -> str:
    """Assemble MD arrays. With ugrd.base.udev, udev rules already ran `mdadm -I`
    incrementally; the scan is just a backstop. Without it (or with only fakeudev,
    which does not run udevd), force MDADM_NO_UDEV=1 and drive assembly from mdadm.conf.
    """
    if "ugrd.base.udev" in self["modules"]:
        return """
    if mdadm_out=$(mdadm --assemble --scan 2>&1); then
        einfo "Assembled MD devices: $mdadm_out"
    else
        edebug "mdadm --assemble --scan returned non-zero (udev may have already assembled): $mdadm_out"
    fi
    """
    return """
    export MDADM_NO_UDEV=1
    if mdadm_out=$(mdadm --assemble --scan 2>&1); then
        einfo "Assembled MD devices: $mdadm_out"
    else
        ewarn "mdadm --assemble --scan returned non-zero: $mdadm_out"
    fi
    """
