from typing import Any, Protocol
from pathlib import Path
from subprocess import CompletedProcess

from zenlib.typing import HasLogger

from ugrd import InitramfsConfig


class InitramfsProtocol(HasLogger, Protocol):
    config_dict: InitramfsConfig
    included_functions: dict[str, str | list[str]]
    build_tasks: list[str]
    init_types: list[str]

    # Add basic definitions for functions defining dict like behavior
    def get(self, item: str, default: Any = None) -> Any: ...
    def __getitem__(self, item: str) -> Any: ...
    def __setitem__(self, item: str, value: Any) -> None: ...
    def __contains__(self, key: str) -> bool: ...

    # Add definitions for helper functions
    def _mkdir(self, path: Path, resolve_build=True) -> None: ...
    def _write(self, file_name: Path | str, contents: list[str] | str, chmod_mask=0o644, append=False) -> None: ...
    def _copy(self, source: Path | str, dest=None) -> None: ...
    def _symlink(self, source: Path | str, target: Path | str) -> None: ...
    def _run(self, args: list[str], timeout=None, fail_silent=False, fail_hard=True) -> CompletedProcess: ...
    def _rotate_old(self, file_name: Path, sequence=0) -> None: ...
    def sort_hook_functions(self, hook: str) -> None: ...

