from pathlib import Path
from subprocess import CompletedProcess
from typing import Any, Protocol

from zenlib.typing import HasLogger

from ugrd import InitramfsConfig


class InitramfsProtocol(HasLogger, Protocol):
    config_dict: InitramfsConfig
    included_functions: dict[str, str | list[str]]
    build_tasks: list[str]
    init_types: list[str]

    # Add basic definitions for functions defining dict like behavior
    def get(self, item: str, default: Any = None) -> Any: ...
    def __getitem__(self, item: str) -> Any: ...
    def __setitem__(self, item: str, value: Any) -> None: ...
    def __contains__(self, key: str) -> bool: ...

    # Add definitions for helper functions
    def _mkdir(self, path: Path, resolve_build: bool = True) -> None: ...
    def _write(
        self, file_name: Path | str, contents: list[str] | str, chmod_mask: int = 0o644, append: bool = False
    ) -> None: ...
    def _copy(self, source: Path | str, dest: Path | str | None = None) -> None: ...
    def _symlink(self, source: Path | str, target: Path | str) -> None: ...
    def _run(
        self, args: list[str], timeout: int | None = None, fail_silent: bool = False, fail_hard: bool = True
        ) -> CompletedProcess: ...  # type: ignore[type-arg]
    def _rotate_old(self, file_name: Path, sequence: int = 0) -> None: ...
    def sort_hook_functions(self, hook: str) -> None: ...
